export { profile, SITE_VERSION } from './profile'
export { products, getProductBySlug, getCompleteProducts } from './products'
export type { Product } from './products'
export { initiatives, getInitiativeBySlug } from './initiatives'
export type { Initiative } from './initiatives'
export { automationItems } from './automation'
export type { AutomationItem } from './automation'
export { timeline } from './timeline'
export type { TimelineItem } from './timeline'
export { philosophyPillars } from './philosophy'
export type { PhilosophyPillar } from './philosophy'
export { terminalCommands, resolveTerminalInput } from './terminal'
