export { profile, SITE_VERSION } from './profile'
export { projects, getFeaturedProjects, getProjectBySlug } from './projects'
export type { Project, ProjectStatus } from './projects'
export { skillCategories } from './skills'
export type { SkillCategory } from './skills'
export { timeline } from './timeline'
export type { TimelineItem } from './timeline'
export { philosophyPillars } from './philosophy'
export type { PhilosophyPillar } from './philosophy'
export { terminalCommands, resolveTerminalInput } from './terminal'
